server:
  port: 8000
spring:
  application:
    name: ADDRESS-SERVICE
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/microservice
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka




