server:
  port: 8010
spring:
  application:
    name: STUDENT-SERVICE
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/microservice
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    instances:
      addressService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 5
        allow-health-indicator-to-fail: true
        register-health-indicator: true
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
#closed : UP
#open : DOWN
#half-open : UNKNOWN